### ISSUE TITLE
The command tries to remove a directory along with files

### ISSUE THREAD

**Issue by AlexanderTunick** [dreamerslab/node.rmdir#14]
I use this:
```
exec('rm -r' + path, function (err, stdout, stderr) {
            if (err) {
            console.log('------------------------------------------------------------------------');
            console.log(' ERROR!!! -- Folder download was not cleaned up before test or it is wrong WARN');
            console.error(err)
            console.log('------------------------------------------------------------------------');
            }

```
and every time it catches callback: 
```
 ERROR!!! -- Folder download was not cleaned up before test or it is wrong WARN
{ Error: Command failed: rm/Users/alexandertunick/Downloads
/bin/sh: rm/Users/alexandertunick/Downloads: No such file or directory

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
  killed: false,
  code: 127,
  signal: null,
  cmd: 'rm/Users/alexandertunick/Downloads' }

```

Even using just **rm** it stays the same.
Everything works fine and ti cleans the directory but this false err might play bad game sometime

**Comment by AlexanderTunick** [comment]
fixed by changing command to **rm -rf** and /path/to/file/*
